version: '3.8'

services:
  jenkins:
    build: ./jenkins/.
    ports:
    - 8020:8080
    volumes:
    - //var/run/docker.sock:/var/run/docker.sock
    - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data: